spring:
  application:
    name: ink-ms-accessibility
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/accessibility_notifications_db
      auto-index-creation: true
  
  main:
    allow-bean-definition-overriding: true

server:
  port: 3004

jwt:
  secret: ${JWT_SECRET:inklusport2024superSecretKeyForJWTtokenGenerationWith512bitsAlgorithmHS512}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.inklusport.accessibility: DEBUG
    org.mongodb.driver: DEBUG